apiVersion: apps/v1
kind: Deployment
metadata:
  name: gubernator
  labels:
    app: gubernator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gubernator
  template:
    metadata:
      labels:
        app: gubernator
    spec:
      containers:
        - image: thrawn01/gubernator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc-port
              containerPort: 81
            - name: http-port
              containerPort: 80
          name: gubernator
          env:
          - name: GUBER_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GUBER_K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          # This should match the port number GRPC is listening on
          # as defined by `containerPort`
          - name: GUBER_K8S_POD_PORT
            value: "81"
          # The selector used when listing endpoints. This selector
          # should only select gubernator peers.
          - name: GUBER_K8S_ENDPOINTS_SELECTOR
            value: "app=gubernator"
          # Enable debug for diagnosing issues
          #- name: GUBER_DEBUG
          #  value: "true"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gubernator
  labels:
    app: gubernator
spec:
  #clusterIP: None
  ports:
  - name: grpc-port
    targetPort: 81
    protocol: TCP
    port: 81
  #- name: http-port
  #targetPort: 80
  #protocol: TCP
  #port: 80
  type: LoadBalancer
  selector:
    app: gubernator
